### ISSUE TITLE
Documentation link is 404

### ISSUE THREAD

**Issue by njt1982** [maxmind/MaxMind-DB-Reader-ruby#8]
https://github.com/maxmind/MaxMind-DB-Reader-ruby/blame/master/README.md#L42

There doesn't seem to be any documentation at https://www.rubydoc.info/gems/maxmind-db?

**Comment by horgh** [comment]
Thanks for pointing this out!

I think it's because the gem version is a prerelease version. There seems to be a bug with yard/rubydoc.info where prerelease gems appear for a short time but then become unavailable (https://github.com/lsegal/yard/issues/1146). I think it'll work again once we do a release with a non-prerelease version.

**Comment by horgh** [comment]
It's working now! Thanks again.
